### ISSUE TITLE
Custom page looking

### ISSUE THREAD

**Issue by titipata** [titipata/titipata.github.io#1]
Add some color on top of the page like color in http://sparanoid.com/ and also small highlight of the section that we're still in (home/about/blog).

**Comment by titipata** [comment]
@bluenex, I think you can do it real quick!

**Comment by bluenex** [comment]
got it will do as you need very soon

**Comment by titipata** [comment]
thanks @bluenex!

**Comment by bluenex** [comment]
here is how it looks like 

![image](https://cloud.githubusercontent.com/assets/11027706/12778686/adba07fc-ca96-11e5-8d16-b5afba390639.png)

and @titipata said that it sucks 😂

Just in case you need a comparison to what @titipata expected

![image](https://cloud.githubusercontent.com/assets/11027706/12778761/2845b0c0-ca97-11e5-9081-d15a505f42ab.png)

**Comment by titipata** [comment]
LOL... completely against my prediction.

**Comment by titipata** [comment]
@bluenex We'll keep it clean like http://motherfuckingwebsite.com/ for now. I'll close the issue
